version: '3.8'
services:
  qr-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-generator
    environment:
      - QR_DATA_URL=https://github.com/Sarachaker
      - QR_CODE_DIR=qr_codes
      - QR_CODE_FILENAME=github_qr.png
      - FILL_COLOR=blue
      - BACK_COLOR=yellow
    volumes:
      - ./qr_codes:/app/qr_codes
